Added diagrams
aqsa-saied-softwire/DevOps-Course-Starter pull request #6
Opened 2024-10-04 09:51 UTC by aqsa-saied-softwire

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2024-10-07 15:19 UTC, Jonesey13 requested changes
Nearly there! It's just missing the component diagram.

2024-10-07 15:19 UTC, Jonesey13 commented on Diagrams/Component.drawio
This diagram appears to be empty?

2024-10-07 15:19 UTC, Jonesey13 commented on Diagrams/context.drawio
This diagram is good for a context diagram. It could include a reference to Trello but that's not too important here.

2024-10-07 15:19 UTC, Jonesey13 commented on Diagrams/Container.drawio
Not too bad for a container diagram but it would be nice to see which component from the previous diagram is being expanded upon here.

2024-10-17 08:42 UTC, aqsa-saied-softwire commented on Diagrams/Component.drawio
Apologies! It hadn't saved my changes so just quickly remade and uploaded

2025-01-24 11:20 UTC, merged